[package]
name = "dir"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
clap = "4.5"
dirs = "5.0"
glob = "0.3.1"
lazy_static = "1.5"
once_cell = "1.19"
serde_json = "1.0"
terminal_size = "0.3"
